spring:
  datasource:
    url: ${SPRING_DATASOURCE_USERNAME:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:bestuser}
    password: ${JDBC_DATABASE_PASSWORD:bestuser}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    ROOT: ERROR

server:
  error:
    include-message: always
  port: ${PORT:8080}